version: '3'
services:

  experiments:
    build: .
    ports:
      - 127.0.0.1:6006:6006
    command: supervisord -n -c /etc/supervisor/supervisord.conf
    volumes:
      - ./experiments:/experiments/ # apply if you want to change the code
      - ./experiments/save:/experiments/save      # log files + tensorboard files; TODO: enable for production
    working_dir: /experiments/

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
