batch_size: 2
calculation: RandomLayer
calculation_args: {}
calculation_seed: 2
circuit_layers: 1
data: MNIST
data_shuffle_seed: 362356
encoder: FRQI_for_2x2
encoder_args: {}
epochs_num: 50
filter_length: 2
img_size: 14
logs_path: ./save/
lr: 0.01
measurement: UniformGateMeasurements
measurement_args: {}
n_rotations: 4
name: Seed_2_Trainable_no_FRQI_for_2x2_2x2_imgsize_14
np_seed: 10
out_channels: 3
out_features: 10
run_test: true
steps_in_epoch: 100
stride: 1
test_samples: 1000
torch_seed: 10
train_samples: 10000
train_split_percent: 0.8
trainable: false
val_data_size: 50
valid_samples: 200
weights_seed: 11111
